/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  future: {
    hoverOnlyWhenSupported: true,
  },
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#c6c6c6",
        "on-secondary-container": "#262626",
        "error": "#ba1a1a",
        "surface-container-high": "#eaeaea",
        "surface-container-low": "#f5f5f5",
        "surface-container": "#f0f0f0",
        "secondary-container": "#e5e5e5",
        "on-secondary-fixed-variant": "#3a3a3a",
        "error-container": "#ffdad6",
        "surface": "#fafafa",
        "tertiary-fixed": "#e2e2e2",
        "outline-variant": "#d4d4d4",
        "on-surface-variant": "#000000",
        "on-tertiary-fixed-variant": "#3a3a3a",
        "on-secondary-fixed": "#141414",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e4e4e4",
        "on-tertiary-fixed": "#141414",
        "outline": "#767676",
        "primary": "#000000",
        "secondary": "#000000",
        "tertiary-fixed-dim": "#c6c6c6",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f0f0f0",
        "primary-fixed-dim": "#111111",
        "on-error-container": "#410002",
        "tertiary-container": "#e0e0e0",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#1a1a1a",
        "primary-fixed": "#e2e2e2",
        "surface-tint": "#111111",
        "tertiary": "#000000",
        "surface-dim": "#dedede",
        "inverse-primary": "#e2e2e2",
        "on-primary-fixed-variant": "#333333",
        "on-background": "#000000",
        "on-secondary": "#ffffff",
        "primary-container": "#000000",
        "on-primary-fixed": "#0a0a0a",
        "background": "#fafafa",
        "on-primary-container": "#ffffff",
        "inverse-surface": "#2a2a2a",
        "surface-bright": "#ffffff",
        "on-error": "#ffffff",
        "secondary-fixed": "#e6e6e6",
        "surface-container-highest": "#e4e4e4",
        "on-surface": "#000000"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "element-gap": "12px",
        "gutter": "16px",
        "section-gap": "64px",
        "unit": "8px",
        "container-padding": "24px"
      },
      fontFamily: {
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "label-sm": ["Space Grotesk", "sans-serif"],
        "label-md": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"]
      },
      fontSize: {
        "headline-xl": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "500"}],
        "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}