/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#dbb8ff",
        "on-secondary-container": "#caa6ef",
        "error": "#ffb4ab",
        "surface-container-high": "#2a2a2a",
        "surface-container-low": "#1b1b1b",
        "surface-container": "#1f1f1f",
        "secondary-container": "#573878",
        "on-secondary-fixed-variant": "#573878",
        "error-container": "#93000a",
        "surface": "#131313",
        "tertiary-fixed": "#e3dfff",
        "outline-variant": "#494454",
        "on-surface-variant": "#cbc3d7",
        "on-tertiary-fixed-variant": "#444173",
        "on-secondary-fixed": "#29074a",
        "surface-container-lowest": "#0e0e0e",
        "surface-variant": "#353535",
        "on-tertiary-fixed": "#181445",
        "outline": "#958ea0",
        "primary": "#d0bcff",
        "secondary": "#dbb8ff",
        "tertiary-fixed-dim": "#c4c1fb",
        "on-tertiary": "#2d2a5b",
        "inverse-on-surface": "#303030",
        "primary-fixed-dim": "#d0bcff",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#8e8bc2",
        "on-primary": "#3c0091",
        "on-tertiary-container": "#262354",
        "primary-fixed": "#e9ddff",
        "surface-tint": "#d0bcff",
        "tertiary": "#c4c1fb",
        "surface-dim": "#131313",
        "inverse-primary": "#6d3bd7",
        "on-primary-fixed-variant": "#5516be",
        "on-background": "#e2e2e2",
        "on-secondary": "#3f2160",
        "primary-container": "#a078ff",
        "on-primary-fixed": "#23005c",
        "background": "#131313",
        "on-primary-container": "#340080",
        "inverse-surface": "#e2e2e2",
        "surface-bright": "#393939",
        "on-error": "#690005",
        "secondary-fixed": "#efdbff",
        "surface-container-highest": "#353535",
        "on-surface": "#e2e2e2"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "element-gap": "12px",
        "gutter": "16px",
        "section-gap": "64px",
        "unit": "8px",
        "container-padding": "24px"
      },
      fontFamily: {
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "label-sm": ["Space Grotesk", "sans-serif"],
        "label-md": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"]
      },
      fontSize: {
        "headline-xl": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "500"}],
        "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}